name: foo

on:
  create

jobs:
  bar:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Parse github.event into environment variables
      - name: Run a one-line script
        run: echo ${{ github.event }}

      # Run script to envsubst tmpl