name: Post-Create Setup

on: create

# Parse github.event into environment variables
env:
  GITHUB_REPOSITORY_NAME: ${{ github.event.create.repository.name }}
  GITHUB_REPOSITORY_DESC: ${{ github.event.create.payload.description }}
  GITHUB_ACTOR_ID: ${{ github.event.create.actor.id }}
  GITHUB_ACTOR_DISPLAY_LOGIN: ${{ github.event.create.actor.display_login }}

jobs:
  envsubst:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run envsubst script
        run: bash .github/post-create.sh
