name: Post-Create Setup

on: create

jobs:
  envsubst:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: GitHub API Request
        uses: octokit/request-action@v2.1.7
        id: get_user
        with:
          route: GET /users/{username}
          username: ${{ github.actor }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run envsubst script
        run: bash .github/envsubst.sh
        env:
          GITHUB_REPOSITORY_NAME: ${{ github.event.repository.name }}
          GITHUB_REPOSITORY_DESC: ${{ github.event.description }}
          GITHUB_ACTOR_ID: ${{ github.actor_id }}
          GITHUB_ACTOR_NAME: ${{ fromJson(steps.get_user.outputs.data).name }}

      - name: Commit and push changes
        run: |
          git config --global user.name "${{ env.GITHUB_ACTOR }}"
          git config --global user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"

          git add -A
          git commit -m "Post-create action commit"
          git push
