name: Post-Create Setup

on: create

# Parse github.event into environment variables
env:
  GITHUB_REPOSITORY_NAME: ${{ github.event.create.repository.name }}
  GITHUB_REPOSITORY_DESC: ${{ github.event.create.description }}
  GITHUB_ACTOR_ID: ${{ github.event.create.sender.id }}
  GITHUB_ACTOR_DISPLAY_LOGIN: ${{ github.event.create.actor.display_login }}

jobs:
  envsubst:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Run envsubst script
        run: bash .github/envsubst.sh

      - name: Commit and push changes
        run: |
          git config --global user.name "${{ github.event.create.actor.display_login }}"
          git config --global user.email "${{ github.event.create.actor.id }}+${{ github.event.create.actor }}@users.noreply.github.com"

          git add -A
          git commit -m "Post-create action commit"
          git push
